import type { DailyActivity } from '../types/dailyActivity'
import type { FollowUp } from '../types/followUp'
import type { PlanGap, DataQualityWarning } from './intelligenceTypes'

export function detectDataQualityWarnings(activities: DailyActivity[], followUps: FollowUp[], planGaps: PlanGap[]): DataQualityWarning[] {
  const warnings: DataQualityWarning[] = []
  for (const activity of activities) {
    const text = `${activity.outcome} ${activity.intelligence} ${activity.nextAction}`
    if (/preliminary|approximate|approximately|requires confirmation/i.test(text)) warnings.push({ severity: 'warning', title: `${activity.account} patient information requires confirmation`, reason: 'The captured information is marked preliminary, approximate, or requiring confirmation.', account: activity.account, sourceActivityId: activity.id })
    for (const outcome of activity.structuredOutcomes) {
      if (outcome.type === 'Patient Access / Access Barrier') warnings.push({ severity: 'warning', title: `${activity.account} has an unresolved access issue`, reason: outcome.details || 'A patient access barrier was recorded.', account: activity.account, sourceActivityId: activity.id })
      if (outcome.type === 'Stock Issue') warnings.push({ severity: 'warning', title: `${activity.account} has a stock issue`, reason: outcome.details || outcome.stockStatus || 'A stock issue was recorded.', account: activity.account, sourceActivityId: activity.id })
      if (outcome.type === 'Issue Unresolved' || /unresolved issue|still unresolved|issue remains unresolved/i.test(`${outcome.details} ${activity.intelligence} ${activity.resolution ?? ''}`)) warnings.push({ severity: 'warning', title: `${activity.account} has an unresolved service issue`, reason: outcome.details || 'A service issue was recorded without a confirmed resolution.', account: activity.account, sourceActivityId: activity.id })
      if (outcome.type === 'Escalation Required' || /escalation required|engineering escalation|escalation/i.test(`${outcome.details} ${activity.escalation ?? ''}`)) warnings.push({ severity: 'warning', title: `${activity.account} requires escalation`, reason: outcome.details || activity.escalation || 'Escalation was recorded for this service issue.', account: activity.account, sourceActivityId: activity.id })
      if ((activity.downtime && /\d/i.test(activity.downtime)) || /downtime|outage|service interruption/i.test(`${activity.intelligence} ${activity.downtime ?? ''}`)) warnings.push({ severity: 'warning', title: `${activity.account} has downtime requiring attention`, reason: activity.downtime || 'A service outage or downtime event was recorded.', account: activity.account, sourceActivityId: activity.id })
      if (/safety concern|unsafe|hazard/i.test(`${outcome.details} ${activity.intelligence} ${activity.issueProblem ?? ''}`)) warnings.push({ severity: 'warning', title: `${activity.account} has a safety concern`, reason: outcome.details || activity.issueProblem || 'A safety concern was recorded.', account: activity.account, sourceActivityId: activity.id })
      if ((outcome.type === 'Issue Unresolved' || outcome.type === 'Issue Partially Resolved') && !activity.resolution?.trim() && !/resolved|fixed|completed|closed/i.test(`${activity.outcome} ${activity.intelligence} ${activity.resolution ?? ''}`)) warnings.push({ severity: 'warning', title: `${activity.account} is missing a clear resolution`, reason: 'This issue remains active but no resolution was captured.', account: activity.account, sourceActivityId: activity.id })
    }
    if (!activity.outcome.trim() && !activity.intelligence.trim() && !activity.nextAction.trim() && activity.structuredOutcomes.length === 0) warnings.push({ severity: 'warning', title: `${activity.account} activity is incomplete`, reason: 'The activity has no outcome, intelligence, next action, or structured outcome recorded.', account: activity.account, sourceActivityId: activity.id })
  }
  for (const followUp of followUps) if (followUp.status === 'open' && followUp.priority === 'high') warnings.push({ severity: 'warning', title: `High-priority follow-up remains open: ${followUp.task}`, reason: 'This follow-up is still open and marked high priority.', account: followUp.facility })
  for (const gap of planGaps) if (gap.status === 'not evidenced') warnings.push({ severity: 'warning', title: `${gap.item} has no captured activity`, reason: gap.reason })
  return warnings.filter((warning, index, all) => all.findIndex((candidate) => candidate.title === warning.title && candidate.sourceActivityId === warning.sourceActivityId) === index)
}